version: '3.1'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: finagle_postgres_test
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
